[package]
name = "rp2040-pac2"
version = "0.1.0"
edition = "2018"

[dependencies]
cortex-m = "0.7.1"
cortex-m-rt = { version = ">=0.6.15,<0.8", optional = true }

[features]
rt = ["cortex-m-rt/device"]
